services:
  miserend:
    image: ghcr.io/szentjozsefhackathon/miserend.hu-coverage:${COVERAGE_IMAGE_TAG:-latest}
    volumes:
      - ../webapp:/miserend/webapp
      - vendor_data:/miserend/webapp/vendor
      - node_modules_data:/miserend/webapp/node_modules
      - ${TEST_RESULTS_PATH:-..}/test-results:/miserend/test-results
      - ${TEST_RESULTS_PATH:-..}/test-results/coverage:/miserend/webapp/tests/coverage
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  vendor_data:
  node_modules_data:
